logging:
  level:
    root: INFO
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL81Dialect
  output:
    ansi:
      enabled: always
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
