# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI
on:
  push:
    branches:
    - '**'
    tags:
     - '**'
  pull_request:
    branches:
     - '**'
    tags:
     - '**'
jobs:
  build:
    name: Build and make test coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17.0.5
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '17.0.5'
        distribution: 'oracle'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.7.0
      env:
           SPRING_PROFILES_ACTIVE: ${{vars.SPRING_PROFILES_ACTIVE}}
           ADMIN_EMAIL: ${{secrets.ADMIN_EMAIL}}
           ADMIN_PASS: ${{secrets.ADMIN_PASS}}
           RSA_PRIVATE: ${{secrets.RSA_PRIVATE}}
           RSA_PUBLIC: ${{secrets.RSA_PUBLIC}}
      with:
          arguments: build
          build-root-directory: ./bank/
    - name: Report test coverage to codeclimate
      uses: paambaati/codeclimate-action@v5.0.0
      env:
           CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
           JACOCO_SOURCE_PATH: ./src/main/java
      with:
           coverageCommand: make report
           coverageLocations: ${{github.workspace}}/bank/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
